# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queueService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12queueService.proto\">\n\x05\x46rame\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0b\n\x03qos\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32-\n\x0cQueueService\x12\x1d\n\tNextFrame\x12\x06.Frame\x1a\x06.Frame\"\x00\x42\x0cZ\n./gRPCspecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queueService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./gRPCspec'
  _globals['_FRAME']._serialized_start=22
  _globals['_FRAME']._serialized_end=84
  _globals['_QUEUESERVICE']._serialized_start=86
  _globals['_QUEUESERVICE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
